// import "./basic.js"
// import "./bindCallApply.js"
// import "./closure.js"
// import "./currying.js"
// import "./hoisting.js"
// import "./pollyfill.js"
// import "./promises"
// import "./prototype.js"
// import "./throtlling.js"
import "./debouncing.js"